/**
 * Password hashing — argon2id.
 *
 * Backend: @node-rs/argon2 — prebuilt native binaries (no node-gyp / C
 * toolchain needed on the build host). Memory-hard algorithm resistant
 * to GPU/ASIC brute force; ~3x faster than bcryptjs in JS.
 *
 * Shared password hashing parameters used by the main app.
 * so hashes generated by one entry-point verify in the other.
 */

import { hash, verify } from "@node-rs/argon2";

// Argon2id parameters — tuned for a single-user home server. These give
// ~80ms hash time on a Raspberry Pi 4, which is fine for a login flow and
// prohibitively expensive for an offline brute-force attacker.
//
// We pass `algorithm: 2` (Argon2id) as a number rather than using the
// `Algorithm` const enum from @node-rs/argon2 — const enums are
// incompatible with `isolatedModules` (the bundler-friendly mode Next.js
// uses for type-checking).
const ARGON2_OPTIONS = {
  algorithm: 2, // Algorithm.Argon2id
  memoryCost: 19456, // 19 MiB
  timeCost: 2,
  parallelism: 1,
};

/** Hash a plaintext password with argon2id. */
export async function hashPassword(plain: string): Promise<string> {
  return hash(plain, ARGON2_OPTIONS);
}

/** Verify a plaintext password against a stored argon2id hash. */
export async function verifyPassword(
  plain: string,
  stored: string
): Promise<boolean> {
  try {
    return await verify(stored, plain);
  } catch {
    // Malformed hash, wrong algorithm, etc. — treat as a failed verify.
    return false;
  }
}
